name: Build Windows App

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, Demo-Tauri ]
    paths:
      - 'tauri-frontend/**'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'tauri-frontend/package-lock.json'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc
    
    - name: Install dependencies
      run: |
        cd tauri-frontend
        npm ci
    
    - name: Build Tauri App
      run: |
        cd tauri-frontend
        npm run tauri build
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: tauri-frontend/src-tauri/target/release/bundle/
        retention-days: 30 