name: Build Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'tauri-frontend/package-lock.json'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-apple-darwin,x86_64-pc-windows-msvc,x86_64-unknown-linux-gnu
    
    - name: Install dependencies (Ubuntu)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf
    
    - name: Install dependencies (Windows)
      if: matrix.platform == 'windows-latest'
      run: |
        choco install -y llvm
    
    - name: Install dependencies
      run: |
        cd tauri-frontend
        npm ci
    
    - name: Build Tauri App
      run: |
        cd tauri-frontend
        npm run tauri build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tauri-app-${{ matrix.platform }}
        path: tauri-frontend/src-tauri/target/release/bundle/ 